sonar.host.url=https://sonarcloud.io
sonar.organization=guilhermewoloszyn
sonar.projectKey=GuilhermeWoloszyn_titantrack
sonar.projectName=TitanTrack - BFF Service

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml